services:
  aaw-mongodb:
    image: mongodb/${MONGODB_IMAGE}:${MONGODB_IMAGE_TAG}
    container_name: aaw-mongodb
    hostname: aaw-mongodb
    restart: ${REPOLICY}
    # security_opt: 
    #   - seccomp:unconfined
      # - no-new-privileges:${PRIVILEGE}
    read_only: ${READ_ONLY}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    # tmpfs:
    #   - /tmp
    volumes:
      - ${MONGO_DB_PATH}:/data/db
      - ${MONGO_DB_CONFIG_PATH}:/data/configdb
    networks:
      - network-aaw
    environment:
      - TZ
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=stock
      
  aaw-mongo-express:
    depends_on:
      - aaw-mongodb
    image: mongo-express:${ME_IMAGE_TAG}
    container_name: aaw-mongo-express
    hostname: aaw-mongo-express
    restart: ${REPOLICY}
    # security_opt: 
    #   - no-new-privileges:${PRIVILEGE}
    read_only: ${READ_ONLY}
    ports:
      - ${MONGO_EX_PORT}:${MONGO_EX_PORT}
    # tmpfs:
    #   - /tmp
    volumes:
      - ${MONGO_EXPRESS_PATH}:/data
    networks:
      - network-aaw
    environment:
      - TZ
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://aaw-mongodb:${MONGO_PORT}
      - ME_CONFIG_MONGODB_SERVER=aaw-mongodb

  aaw-web:
    depends_on:
      - aaw-mongo-express
    build: 
      dockerfile: Dockerfile
    hostname: aaw-web
    restart: ${REPOLICY}
    security_opt:
      - no-new-privileges:${PRIVILEGE}
    read_only: ${READ_ONLY}
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/home
    networks:
      - network-aaw

networks:
  network-aaw:
    driver: bridge